exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "test",
    "tests",
]

line-length = 90
indent-width = 4

[lint]
select = ["ALL"]
ignore = []
unfixable = ["B"]

[lint.per-file-ignores]
"vesync.py" = ["F403"]

[lint.pep8-naming]
extend-ignore-names = ["displayJSON"]

[lint.pydocstyle]
convention = "google"

[lint.pylint]
max-public-methods = 30

[format]
quote-style =  "preserve"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"

